import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import { MyHeader } from "@/components/Header/header";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import ContextProvider from "@/components/contextApi/contextApi";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: "300"
});

export const metadata: Metadata = {
  title: "Minha página pessoal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={ubuntu.className}>
        <ContextProvider>
          <AppRouterCacheProvider>
            <MyHeader />
            {children}
          </AppRouterCacheProvider>
        </ContextProvider>
      </body>
    </html>
  );
}
